/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Crisp Primary Operational Palette
        "primary": "#1872F5",
        "primary-hover": "#1464CC",
        "primary-container": "#1464CC",
        "primary-fixed": "#DCE8FE",
        "primary-fixed-dim": "#BFD7FE",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#FFFFFF",
        "on-primary-fixed": "#0B3C8A",
        "on-primary-fixed-variant": "#1464CC",
        
        // Crisp Black & Neutrals
        "crisp-black": "#1C293C",
        "secondary": "#414754",
        "secondary-container": "#F1F5F9",
        "secondary-fixed": "#E2E8F0",
        "secondary-fixed-dim": "#CBD5E1",
        "on-secondary": "#FFFFFF",
        "on-secondary-container": "#1C293C",
        "on-secondary-fixed": "#1C293C",
        "on-secondary-fixed-variant": "#414754",

        "tertiary": "#1464CC",
        "tertiary-container": "#EEF4FF",
        "tertiary-fixed": "#DCE8FE",
        "tertiary-fixed-dim": "#BFD7FE",
        "on-tertiary": "#FFFFFF",
        "on-tertiary-container": "#1872F5",
        "on-tertiary-fixed": "#0B3C8A",
        "on-tertiary-fixed-variant": "#1464CC",

        // Crisp Canvas & Surfaces (Clean SaaS Palette)
        "canvas": "#F4F7F8",
        "background": "#F4F7F8",
        "on-background": "#1C293C",
        
        "surface": "#FFFFFF",
        "surface-bright": "#FFFFFF",
        "surface-dim": "#F1F5F9",
        "surface-variant": "#F4F7F8",
        "surface-tint": "#1464CC",
        "surface-container": "#F4F7F8",
        "surface-container-low": "#F4F7F8",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-high": "#EEF2F6",
        "surface-container-highest": "#D9E6E8",
        
        "on-surface": "#1C293C",
        "on-surface-variant": "#414754",
        
        // Crisp 1px Borders & Dividers
        "outline": "#D9E6E8",
        "outline-variant": "#D9E6E8",
        "border-subtle": "#D9E6E8",

        // Crisp Shared Foundation Tag Segments (Reference Image Exact)
        "sea-green": "#41B57A",
        "sea-green-light": "#E1F3E9",
        "tag-green": "#41B57A",
        "tag-green-light": "#E1F3E9",

        "lemon-curry": "#C3A108",
        "lemon-curry-light": "#FCFBED",
        "tag-yellow": "#C3A108",
        "tag-yellow-light": "#FCFBED",

        "ochre": "#E07414",
        "ochre-light": "#FEF4EC",
        "tag-ochre": "#E07414",
        "tag-ochre-light": "#FEF4EC",

        "majorette-purple": "#8F53F2",
        "majorette-purple-light": "#F1EDFE",
        "tag-purple": "#8F53F2",
        "tag-purple-light": "#F1EDFE",

        // Alert & Critical
        "error": "#E02020",
        "error-container": "#FEE2E2",
        "on-error": "#FFFFFF",
        "on-error-container": "#991B1B",
        "tag-red": "#E02020",
        "tag-red-light": "#FEE2E2",

        "inverse-surface": "#1C293C",
        "inverse-on-surface": "#F4F7F8",
        "inverse-primary": "#BFD7FE",

        // Palette overrides to align default tailwind color usages to Crisp Foundation
        emerald: {
          50: "#F0FDF4",
          100: "#E1F3E9",
          500: "#41B57A",
          600: "#2B8756",
          700: "#1C6B42",
          800: "#155232",
        },
        green: {
          50: "#F0FDF4",
          100: "#E1F3E9",
          500: "#41B57A",
          600: "#2B8756",
          700: "#1C6B42",
          800: "#155232",
        },
        amber: {
          50: "#FFFBEB",
          100: "#FCFBED",
          500: "#C3A108",
          600: "#967804",
          700: "#755E03",
          800: "#574602",
        },
        yellow: {
          50: "#FEFCE8",
          100: "#FCFBED",
          500: "#C3A108",
          600: "#967804",
          700: "#755E03",
          800: "#574602",
        },
        orange: {
          50: "#FFF7ED",
          100: "#FEF4EC",
          500: "#E07414",
          600: "#B85708",
          700: "#8C4004",
          800: "#692F03",
        },
        purple: {
          50: "#FAF5FF",
          100: "#F1EDFE",
          500: "#8F53F2",
          600: "#7435DF",
          700: "#5C25B8",
          800: "#471B91",
        },
        blue: {
          50: "#EEF4FF",
          100: "#DCE8FE",
          500: "#1872F5",
          600: "#1464CC",
          700: "#0F4DA0",
          800: "#0B3C8A",
        },
        slate: {
          50: "#F8FAFC",
          100: "#F4F7F8",
          200: "#D9E6E8",
          300: "#CBD5E1",
          400: "#94A3B8",
          500: "#64748B",
          600: "#414754",
          700: "#334155",
          800: "#1E293B",
          900: "#1C293C",
        },
      },
      borderRadius: {
        "none": "0px",
        "sm": "4px",
        "DEFAULT": "8px",
        "md": "8px",
        "lg": "8px",
        "xl": "12px",
        "2xl": "12px",
        "3xl": "12px",
        "full": "9999px",
      },
      spacing: {
        "unit": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "gutter": "20px",
        "margin-page": "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["Figtree", "'Proxima Nova'", "Inter", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Roboto", "sans-serif"],
        "display": ["Figtree", "'Proxima Nova'", "Inter", "sans-serif"],
        "headline-lg": ["Figtree", "'Proxima Nova'", "Inter", "sans-serif"],
        "headline-md": ["Figtree", "'Proxima Nova'", "Inter", "sans-serif"],
        "body-lg": ["Figtree", "'Proxima Nova'", "Inter", "sans-serif"],
        "body-md": ["Figtree", "'Proxima Nova'", "Inter", "sans-serif"],
        "body-sm": ["Figtree", "'Proxima Nova'", "Inter", "sans-serif"],
        "label-md": ["Figtree", "'Proxima Nova'", "Inter", "sans-serif"],
        "data-tabular": ["Figtree", "'Proxima Nova'", "Inter", "monospace"],
        mono: ["Figtree", "'Proxima Nova'", "Inter", "monospace"],
      },
      fontSize: {
        "display": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "data-tabular": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
      boxShadow: {
        "none": "none",
        "xs": "none",
        "sm": "none",
        "card": "none",
        "popover": "0 10px 25px -5px rgba(28, 41, 60, 0.08), 0 8px 10px -6px rgba(28, 41, 60, 0.04)",
        "modal": "0 20px 25px -5px rgba(28, 41, 60, 0.12), 0 10px 10px -5px rgba(28, 41, 60, 0.06)",
      },
    },
  },
  plugins: [],
}
